### ISSUE TITLE
project needs screenshots and info on activity/roadmap

### ISSUE THREAD

**Issue by GoZippy** [morph1904/PYNginx#18]
found you on Reddit post - looked at Tyger - seems abandoned now. Is this the updated setup you use? I am looking for something similar and would like to see how it all works... need any help on anything?
Maybe spin up a redmine server for devs or use git issues...

**Comment by morph1904** [comment]
Hi I think you might be looking for TygerCaddy and can be seen here: https://tygercaddy.co.uk or https://hub.docker.com/r/morph1904/tygercaddy This is the latest version of Tyger and is due to come out of Beta soon.

**Comment by GoZippy** [comment]
Thanks for the docker link... I'm gong to test it out right now.

**Comment by GoZippy** [comment]
https://tygercaddy.co.uk/

By the way goes to blank page for me in USA

**Comment by morph1904** [comment]
Yeah issue started this afternoon. I have a problem with a load balancer.
If you refresh the page after it first loads, it loads properly. Will get
around to fixing that tomorrow! Thanks for letting me know though.

**Comment by GoZippy** [comment]
It's working now.

Any advice for me to run this? I'm using Dell r210ii servers. I have 40 of
them...

I have been playing with proxmox and CEPH with docker on it in an lxc
container with high availability setup so any vm or lxc will fail over
across the cluster...

 I'm wanting to have a couple nodes physically connected to ISP modem, I
have 5 static ip addresses...

Right now I don't have backup ip but will install a 4G/5G cell phone as
backup data. Will want to figure out how to do a mini sdwan solution from
home..


Anyhow I'm wanting reverse proxy in high availability over multiple nodes
to be able to roue back out to internet for certain domains and to internal
private lan proxmox hosted vm/lxc's...

I'm really loving the speed of spinning up instances and migration over
esxi...proxmox is great.
